import MeetingController from "./MeetingController";
import {
  CreateMeetingSchema,
  JoinMeetingSchema,
  LeaveMeetingSchema,
  UpcomingMeetingsSchema,
  ShareMeetingLinkSchema,
  RedirectMeetingSchema,
} from "./MeetingModels/MeetingValidation";

export const MeetingRoute = [
  {
    path: "/meetings/create",
    request: CreateMeetingSchema,
    action: MeetingController.CreateMeeting,
    method: "post",
  },
  {
    path: "/meetings/join",
    request: JoinMeetingSchema,
    action: MeetingController.JoinMeeting,
    method: "post",
  },
  {
    path: "/meetings/share-link",
    request: ShareMeetingLinkSchema,
    action: MeetingController.CreateShareLink,
    method: "post",
    roles: ["admin"],
  },
  {
    path: "/meetings/redirect",
    request: RedirectMeetingSchema,
    action: MeetingController.RedirectMeeting,
    method: "post",
  },
  {
    path: "/open/class/:meetingId",
    request: null,
    action: MeetingController.DeepLinkRedirect,
    method: "get",
  },
  {
    path: "/meetings/upcoming",
    request: UpcomingMeetingsSchema,
    action: MeetingController.GetUpcomingMeetings,
    method: "get",
  },
  {
    path: "/meetings/all",
    request: null,
    action: MeetingController.GetAllMeetings,
    method: "get",
  },
  {
    path: "/meetings/weekly-activity",
    request: null,
    action: MeetingController.getWeeklyActivity,
    method: "get",
  },
  {
    path: "/meetings/today",
    request: UpcomingMeetingsSchema,
    action: MeetingController.GetTodaysMeetings,
    method: "get",
  },
    {
    path: "/meetings/:id/recording",
    request: null,
    action: MeetingController.GetMeetingRecording,
    method: "get",
  },
  {
    path: "/meetings/weekly",
    request: null,
    action: MeetingController.GetWeeklyMeetings,
    method: "get",
  },
  {
    path: "/meetings/by-day/:dayIndex",
    request: null,
    action: MeetingController.GetMeetingsByDay,
    method: "get",
  },
  {
    path: "/meetings/trainer/upcoming",
    request: UpcomingMeetingsSchema,
    action: MeetingController.GetTrainerUpcomingMeetings,
    method: "get",
  },
  {
    path: "/meetings/getAll",
    request: null,
    action: MeetingController.getAllMeetings,
    method: "get",
  },
  {
    path: "/meetings/past",
    request: null,
    action: MeetingController.GetPastSessions,
    method: "get",
  },
  {
    path: "/meetings/session-history",
    request: null,
    action: MeetingController.GetSessionHistory,
    method: "get",
  },
  {
    path: "/meetings/completed-sessions",
    request: null,
    action: MeetingController.getSessionsWithPagination,
    method: "get",
  },
  {
    path: "/meetings/getAllTrainerMeetings",
    request: null,
    action: MeetingController.GetAllTrainerMeetings,
    method: "get",
  },
  {
    path: "/meetings/attendance/monthly",
    request: null,
    action: MeetingController.GetMonthlyAttendance,
    method: "get",
  },
  {
    path: "/meetings/:id",
    request: null,
    action: MeetingController.GetMeetingById,
    method: "get",
  },
  {
    path: "/meetings/:id",
    request: null,
    action: MeetingController.UpdateMeeting,
    method: "patch",
  },
  {
    path: "/meetings/:id",
    request: null,
    action: MeetingController.DeleteMeeting,
    method: "delete",
  },
];